from django.db import models


class SpellsNew(models.Model):
    """
    This model maps to the spells_new table in the database.
    """
    id = models.IntegerField(primary_key=True, null=False, default=0)
    name = models.CharField(max_length=64, null=True, default=None)
    player_1 = models.CharField(max_length=64, null=True, default='BLUE_TRAIL')
    teleport_zone = models.CharField(max_length=64, null=True, default=None)
    you_cast = models.CharField(max_length=120, null=True, default=None)
    other_casts = models.CharField(max_length=120, null=True, default=None)
    cast_on_you = models.CharField(max_length=120, null=True, default=None)
    cast_on_other = models.CharField(max_length=120, null=True, default=None)
    spell_fades = models.CharField(max_length=120, null=True, default=None)
    range = models.IntegerField(null=False, default=100)
    aoe_range = models.IntegerField(null=False, default=0, db_column='aoerange')
    pushback = models.FloatField(null=False, default=0.0)
    pushup = models.FloatField(null=False, default=0.0)
    cast_time = models.IntegerField(null=False, default=0)
    recovery_time = models.IntegerField(null=False, default=0)
    recast_time = models.IntegerField(null=False, default=0)
    buff_duration_formula = models.IntegerField(null=False, default=7, db_column='buffdurationformula')
    buff_duration = models.IntegerField(null=False, default=0, db_column='buffduration')
    AEDuration = models.IntegerField(null=False, default=0)
    mana = models.IntegerField(null=False, default=0)
    effect_base_value1 = models.IntegerField(null=True, default=100)
    effect_base_value2 = models.IntegerField(null=True, default=0)
    effect_base_value3 = models.IntegerField(null=True, default=0)
    effect_base_value4 = models.IntegerField(null=True, default=0)
    effect_base_value5 = models.IntegerField(null=True, default=0)
    effect_base_value6 = models.IntegerField(null=True, default=0)
    effect_base_value7 = models.IntegerField(null=True, default=0)
    effect_base_value8 = models.IntegerField(null=True, default=0)
    effect_base_value9 = models.IntegerField(null=True, default=0)
    effect_base_value10 = models.IntegerField(null=True, default=0)
    effect_base_value11 = models.IntegerField(null=True, default=0)
    effect_base_value12 = models.IntegerField(null=True, default=0)
    effect_limit_value1 = models.IntegerField(null=False, default=0)
    effect_limit_value2 = models.IntegerField(null=False, default=0)
    effect_limit_value3 = models.IntegerField(null=False, default=0)
    effect_limit_value4 = models.IntegerField(null=False, default=0)
    effect_limit_value5 = models.IntegerField(null=False, default=0)
    effect_limit_value6 = models.IntegerField(null=False, default=0)
    effect_limit_value7 = models.IntegerField(null=False, default=0)
    effect_limit_value8 = models.IntegerField(null=False, default=0)
    effect_limit_value9 = models.IntegerField(null=False, default=0)
    effect_limit_value10 = models.IntegerField(null=False, default=0)
    effect_limit_value11 = models.IntegerField(null=False, default=0)
    effect_limit_value12 = models.IntegerField(null=False, default=0)
    max1 = models.IntegerField(null=False, default=0)
    max2 = models.IntegerField(null=False, default=0)
    max3 = models.IntegerField(null=False, default=0)
    max4 = models.IntegerField(null=False, default=0)
    max5 = models.IntegerField(null=False, default=0)
    max6 = models.IntegerField(null=False, default=0)
    max7 = models.IntegerField(null=False, default=0)
    max8 = models.IntegerField(null=False, default=0)
    max9 = models.IntegerField(null=False, default=0)
    max10 = models.IntegerField(null=False, default=0)
    max11 = models.IntegerField(null=False, default=0)
    max12 = models.IntegerField(null=False, default=0)
    icon = models.IntegerField(null=False, default=0)
    mem_icon = models.IntegerField(null=False, default=0, db_column='memicon')
    components1 = models.IntegerField(null=False, default=-1)
    components2 = models.IntegerField(null=False, default=-1)
    components3 = models.IntegerField(null=False, default=-1)
    components4 = models.IntegerField(null=False, default=-1)
    component_counts1 = models.IntegerField(null=False, default=1)
    component_counts2 = models.IntegerField(null=False, default=1)
    component_counts3 = models.IntegerField(null=False, default=1)
    component_counts4 = models.IntegerField(null=False, default=1)
    NoexpendReagent1 = models.IntegerField(null=False, default=-1)
    NoexpendReagent2 = models.IntegerField(null=False, default=-1)
    NoexpendReagent3 = models.IntegerField(null=False, default=-1)
    NoexpendReagent4 = models.IntegerField(null=False, default=-1)
    formula1 = models.IntegerField(null=False, default=100)
    formula2 = models.IntegerField(null=False, default=100)
    formula3 = models.IntegerField(null=False, default=100)
    formula4 = models.IntegerField(null=False, default=100)
    formula5 = models.IntegerField(null=False, default=100)
    formula6 = models.IntegerField(null=False, default=100)
    formula7 = models.IntegerField(null=False, default=100)
    formula8 = models.IntegerField(null=False, default=100)
    formula9 = models.IntegerField(null=False, default=100)
    formula10 = models.IntegerField(null=False, default=100)
    formula11 = models.IntegerField(null=False, default=100)
    formula12 = models.IntegerField(null=False, default=100)
    LightType = models.IntegerField(null=False, default=0)
    goodEffect = models.IntegerField(null=False, default=0)
    Activated = models.IntegerField(null=False, default=0)
    resist_type = models.IntegerField(null=False, default=0, db_column='resisttype')
    effectid1 = models.IntegerField(null=True, default=254)
    effectid2 = models.IntegerField(null=True, default=254)
    effectid3 = models.IntegerField(null=True, default=254)
    effectid4 = models.IntegerField(null=True, default=254)
    effectid5 = models.IntegerField(null=True, default=254)
    effectid6 = models.IntegerField(null=True, default=254)
    effectid7 = models.IntegerField(null=True, default=254)
    effectid8 = models.IntegerField(null=True, default=254)
    effectid9 = models.IntegerField(null=True, default=254)
    effectid10 = models.IntegerField(null=True, default=254)
    effectid11 = models.IntegerField(null=True, default=254)
    effectid12 = models.IntegerField(null=True, default=254)
    target_type = models.IntegerField(null=False, default=2, db_column='targettype')
    base_diff = models.IntegerField(null=False, default=0, db_column='basediff')
    skill = models.IntegerField(null=False, default=98)
    zone_type = models.IntegerField(null=False, default=-1, db_column='zonetype')
    environment_type = models.IntegerField(null=False, default=0, db_column='EnvironmentType')
    time_of_day = models.IntegerField(null=False, default=0, db_column='TimeOfDay')
    classes1 = models.IntegerField(null=True, default=255)
    classes2 = models.IntegerField(null=True, default=255)
    classes3 = models.IntegerField(null=True, default=255)
    classes4 = models.IntegerField(null=True, default=255)
    classes5 = models.IntegerField(null=True, default=255)
    classes6 = models.IntegerField(null=True, default=255)
    classes7 = models.IntegerField(null=True, default=255)
    classes8 = models.IntegerField(null=True, default=255)
    classes9 = models.IntegerField(null=True, default=255)
    classes10 = models.IntegerField(null=True, default=255)
    classes11 = models.IntegerField(null=True, default=255)
    classes12 = models.IntegerField(null=True, default=255)
    classes13 = models.IntegerField(null=True, default=255)
    classes14 = models.IntegerField(null=True, default=255)
    classes15 = models.IntegerField(null=True, default=255)
    custom_icon = models.IntegerField(null=True, default=0)
    new_icon = models.IntegerField(null=False, default=161)
    not_player_spell = models.IntegerField(null=True, default=0)
    resist_diff = models.IntegerField(null=False, default=-150, db_column='resistdiff')
    spell_category = models.IntegerField(null=False, default=-99)

    class Meta:
        db_table = 'spells_new'
        managed = False

