# Generated by Django 5.1.4 on 2026-03-22 18:20

import django.core.validators
import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS class or icon reference', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Quest Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestFactionLowered',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lowered Faction',
                'verbose_name_plural': 'Lowered Factions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestFactionRaised',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Raised Faction',
                'verbose_name_plural': 'Raised Factions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestFactionRequired',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Required Faction',
                'verbose_name_plural': 'Required Factions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=0)),
                ('Name', models.CharField(default=0, max_length=64)),
            ],
            options={
                'verbose_name': 'Quest Item',
                'verbose_name_plural': 'Quest Items',
                'ordering': ['Name'],
                'indexes': [models.Index(fields=['item_id'], name='item_id_idx'), models.Index(fields=['Name'], name='item_name_idx')],
                'unique_together': {('item_id', 'Name')},
            },
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', mdeditor.fields.MDTextField(blank=True, default='', null=True)),
                ('starting_npc_id', models.IntegerField(default=0)),
                ('starting_zone', models.CharField(choices=[('Unused', 'Unused'), ('acrylia', 'Acrylia Caverns'), ('airplane', 'The Plane of Sky'), ('akanon', "Ak'Anon"), ('akheva', 'Akheva Ruins'), ('arena', 'The Arena'), ('aviak', 'Aviak Village'), ('bazaar', 'The Bazaar'), ('befallen', 'Befallen'), ('beholder', 'Gorge of King Xorbb'), ('blackburrow', 'Blackburrow'), ('burningwood', 'The Burning Wood'), ('butcher', 'Butcherblock Mountains'), ('cabeast', 'Cabilis East'), ('cabwest', 'Cabilis West'), ('cauldron', "Dagnor's Cauldron"), ('cazicthule', 'Accursed Temple of CazicThule'), ('charasis', 'The Howling Stones'), ('chardok', 'Chardok'), ('citymist', 'The City of Mist'), ('cobaltscar', 'Cobalt Scar'), ('commons', 'West Commonlands'), ('crushbone', 'Crushbone'), ('crystal', 'Crystal Caverns'), ('cshome', 'Sunset Home'), ('dalnir', 'The Crypt of Dalnir'), ('dawnshroud', 'Dawnshroud'), ('dreadlands', 'The Dreadlands'), ('droga', 'The Temple of Droga'), ('eastkarana', 'Eastern Plains of Karana'), ('eastwastes', 'Eastern Wastes'), ('echo', 'Echo Caverns'), ('ecommons', 'East Commonlands'), ('emeraldjungle', 'The Emerald Jungle'), ('erudnext', 'Erudin'), ('erudnint', 'The Erudin Palace'), ('erudsxing', "Erud's Crossing"), ('erudsxing2', "Marauder's Mire"), ('everfrost', 'Everfrost Peaks'), ('fearplane', 'The Plane of Fear'), ('feerrott', 'The Feerott'), ('felwithea', 'Northern Felwithe'), ('felwitheb', 'Southern Felwithe'), ('fieldofbone', 'The Field of Bone'), ('firiona', 'Firiona Vie'), ('freporte', 'East Freeport'), ('freportn', 'North Freeport'), ('freportw', 'West Freeport'), ('frontiermtns', 'Frontier Mountains'), ('frozenshadow', 'Tower of Frozen Shadow'), ('fungusgrove', 'The Fungus Grove'), ('gfaydark', 'The Greater Faydark'), ('greatdivide', 'The Great Divide'), ('griegsend', "Grieg's End"), ('grimling', 'The Grimling Forest'), ('grobb', 'Grobb'), ('growthplane', 'Plane of Growth'), ('gukbottom', 'The Ruins of Old Guk'), ('guktop', 'The City of Guk'), ('halas', 'Halas'), ('hateplane', 'Plane of Hate'), ('highkeep', 'High Keep'), ('highpass', 'Highpass Hold'), ('hole', 'The Hole'), ('hollowshade', 'Hollowshade Moor'), ('iceclad', 'Iceclad Ocean'), ('innothule', 'Innothule Swamp'), ('jaggedpine', 'Jaggedpine Forest'), ('kael', 'Kael Drakkel'), ('kaesora', 'Kaesora'), ('kaladima', 'South Kaladim'), ('kaladimb', 'North Kaladim'), ('karnor', "Karnor's Castle"), ('katta', 'Katta Castellum'), ('kedge', 'Kedge Keep'), ('kerraridge', 'Kerra Isle'), ('kithicor', 'Kithicor Forest'), ('kurn', "Kurn's Tower"), ('lakeofillomen', 'Lake of Ill Omen'), ('lakerathe', 'Lake Rathetear'), ('lavastorm', 'The Lavastorm Mountains'), ('letalis', 'Mons Letalis'), ('lfaydark', 'The Lesser Faydark'), ('maiden', "Maiden's Eye"), ('mischiefplane', 'Plane of Mischief'), ('mistmoore', 'The Castle of Mistmoore'), ('misty', 'Misty Thicket'), ('mseru', 'Marus Seru'), ('najena', 'Najena'), ('necropolis', 'Dragon Necropolis'), ('nektropos', 'Nektropos'), ('nektulos', 'The Nektulos Forest'), ('neriaka', 'Neriak - Foreign Quarter'), ('neriakb', 'Neriak - Commons'), ('neriakc', 'Neriak - 3rd Gate'), ('neriakd', 'Neriak Palace'), ('netherbian', 'Netherbian Lair'), ('nexus', 'The Nexus'), ('northkarana', 'The Northern Plains of Karana'), ('nro', 'Northern Desert of Ro'), ('nurga', 'The Mines of Nurga'), ('oasis', 'Oasis of Marr'), ('oggok', 'Oggok'), ('oot', 'Ocean of Tears'), ('overthere', 'The Overthere'), ('paineel', 'Paineel'), ('paludal', 'The Paludal Caverns'), ('paw', 'The Lair of the Splitpaw'), ('permafrost', 'The Permafrost Caverns'), ('poknowledge', 'Plane of Knowledge'), ('qcat', 'The Qeynos Aqueduct System'), ('qey2hh1', 'The Western Plains of Karana'), ('qeynos', 'South Qeynos'), ('qeynos2', 'North Qeynos'), ('qeytoqrg', 'The Qeynos Hills'), ('qrg', 'The Surefall Glade'), ('rathemtn', 'The Rathe Mountains'), ('rivervale', 'Rivervale'), ('runnyeye', 'The Liberated Citadel of Runnyeye'), ('scarlet', 'Scarlet Desert'), ('sebilis', 'The Ruins of Sebilis'), ('shadeweaver', "Shadeweaver's Thicket"), ('shadowhaven', 'Shadow Haven'), ('sharvahl', 'The City of Sharvahl'), ('sirens', "Siren's Grotto"), ('skyfire', 'The Skyfire Mountains'), ('skyshrine', 'Skyshrine'), ('sleeper', "Sleeper's Tomb"), ('soldunga', "Solusek's Eye"), ('soldungb', "Nagafen's Lair"), ('soltemple', 'The Temple of Solusek Ro'), ('southkarana', 'The Southern Plains of Karana'), ('sro', 'Southern Desert of Ro'), ('sseru', 'Sanctus Seru'), ('ssratemple', 'Ssraeshza Temple'), ('steamfont', 'Steamfont Mountains'), ('stonebrunt', 'The Stonebrunt Mountains'), ('swampofnohope', 'The Swamp of No Hope'), ('templeveeshan', 'Temple of Veeshan'), ('tenebrous', 'The Tenebrous Mountains'), ('thedeep', 'The Deep'), ('thegrey', 'The Grey'), ('thurgadina', 'The City of Thurgadin'), ('thurgadinb', 'Icewell Keep'), ('timorous', 'Timorous Deep'), ('tox', 'Toxxulia Forest'), ('trakanon', "Trakanon's Teeth"), ('twilight', 'Twilight Sea'), ('umbral', 'The Umbral Plains'), ('unrest', 'The Estate of Unrest'), ('unused', 'Unused'), ('veeshan', "Veeshan's Peak"), ('veksar', 'Veksar'), ('velketor', "Velketor's Labryninth"), ('vexthal', 'Vex Thal'), ('wakening', 'The Wakening Lands'), ('warrens', 'The Warrens'), ('warslikswood', 'The Warsliks Woods'), ('westwastes', 'Western Wastes')], max_length=100)),
                ('expansion_introduced', models.SmallIntegerField(choices=[(0, 'Vanilla'), (1, 'The Ruins of Kunark'), (2, 'The Scars of Velious'), (3, 'The Shadows of Luclin'), (4, 'The Planes of Power'), (5, 'The Legacy of Ykesha '), (6, 'Lost Dungeons of Norrath'), (7, 'Gates of Discord'), (8, 'Omens of War'), (9, 'Dragons of Norrath'), (10, 'Depths of Darkhollow')], default=0, null=True)),
                ('minimum_level', models.SmallIntegerField(default=1, null=True)),
                ('maximum_level', models.SmallIntegerField(default=-1, null=True)),
                ('class_restrictions', models.IntegerField(choices=[(-1, 'None'), (0, 'Unknown'), (1, 'Warrior'), (2, 'Cleric'), (3, 'Paladin'), (4, 'Ranger'), (5, 'Shadowknight'), (6, 'Druid'), (7, 'Monk'), (8, 'Bard'), (9, 'Rogue'), (10, 'Shaman'), (11, 'Necromancer'), (12, 'Wizard'), (13, 'Magician'), (14, 'Enchanter'), (15, 'Beastlord')], default=0)),
                ('race_restrictions', models.IntegerField(choices=[(-1, 'None'), (0, 'Unknown'), (1, 'Human'), (2, 'Barbarian'), (3, 'Erudite'), (4, 'Wood Elf'), (5, 'High Elf'), (6, 'Dark Elf'), (7, 'Half Elf'), (8, 'Dwarf'), (9, 'Troll'), (10, 'Ogre'), (11, 'Halfling'), (12, 'Gnome'), (13, 'Iksar'), (14, 'Vah Shir'), (128, 'Iksar')], default=0)),
                ('deity_restrictions', models.IntegerField(choices=[(-1, 'None'), (140, 'Agnostic'), (396, 'Agnostic'), (201, 'Bertoxxulous'), (202, 'Brell Serilis'), (203, 'Cazic Thule'), (204, 'Erollisi Marr'), (205, 'Bristlebane'), (206, 'Innoruuk'), (207, 'Karana'), (208, 'Mithaniel Marr'), (209, 'Prexus'), (210, 'Quellious'), (211, 'Rallos Zek'), (212, 'Rodcet Nife'), (213, 'Solusek Ro'), (214, 'The Tribunal'), (215, 'Tunare'), (216, 'Veeshan')], default=0)),
                ('is_repeatable', models.BooleanField(default=True)),
                ('monster_mission', models.BooleanField(default=False)),
                ('quest_reward', models.JSONField(blank=True, default=dict, help_text="Reward data like {'item_id': 123, 'faction': 'Guardians', 'exp': 500, 'flag': 'completed_zone'}")),
                ('difficulty_rating', models.SmallIntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], default=3)),
                ('estimated_time', models.CharField(blank=True, help_text='Estimated time to complete', max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='quests.questcategory')),
                ('factions_lowered', models.ManyToManyField(blank=True, related_name='lowered_for_quests', to='quests.questfactionlowered')),
                ('factions_raised', models.ManyToManyField(blank=True, related_name='raised_for_quests', to='quests.questfactionraised')),
                ('factions_required', models.ManyToManyField(blank=True, related_name='required_for_quests', to='quests.questfactionrequired')),
                ('quest_items', models.ManyToManyField(blank=True, related_name='quests', to='quests.questitem')),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
                'db_table': 'quests',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExperienceReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_percentage', models.BooleanField(default=False, help_text='Whether this is a percentage of level or flat amount')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Experience Reward',
                'verbose_name_plural': 'Experience Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('platinum', models.PositiveIntegerField(default=0)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('silver', models.PositiveIntegerField(default=0)),
                ('copper', models.PositiveIntegerField(default=0)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Currency Reward',
                'verbose_name_plural': 'Currency Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AAReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('aa_id', models.IntegerField(blank=True, null=True)),
                ('aa_name', models.CharField(max_length=100)),
                ('aa_points', models.PositiveIntegerField(default=1)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'AA Reward',
                'verbose_name_plural': 'AA Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestsRelatedNPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_id', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Quest Related NPC',
                'verbose_name_plural': 'Quest Related NPCs',
                'db_table': 'quests_related_npc',
                'ordering': ['name'],
                'managed': True,
                'indexes': [models.Index(fields=['npc_id'], name='npc_id_idx'), models.Index(fields=['name'], name='npc_name_idx')],
            },
        ),
        migrations.AddField(
            model_name='quests',
            name='related_npcs',
            field=models.ManyToManyField(blank=True, related_name='quests', to='quests.questsrelatednpc'),
        ),
        migrations.CreateModel(
            name='QuestsRelatedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(default=0)),
                ('long_name', models.TextField()),
                ('short_name', models.CharField(max_length=32, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Quest Related Zone',
                'verbose_name_plural': 'Quest Related Zones',
                'db_table': 'quests_related_zone',
                'ordering': ['short_name'],
                'managed': True,
                'indexes': [models.Index(fields=['short_name'], name='short_name_idx'), models.Index(fields=['zone_id'], name='zone_id_idx')],
            },
        ),
        migrations.AddField(
            model_name='quests',
            name='related_zones',
            field=models.ManyToManyField(blank=True, related_name='quests', to='quests.questsrelatedzone'),
        ),
        migrations.AddField(
            model_name='quests',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='quests', to='quests.questtag'),
        ),
        migrations.CreateModel(
            name='SkillReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('skill_id', models.IntegerField(blank=True, null=True)),
                ('skill_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(default=1, help_text='Skill points gained')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Skill Reward',
                'verbose_name_plural': 'Skill Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('spell_id', models.IntegerField()),
                ('spell_name', models.CharField(max_length=100)),
                ('spell_level', models.PositiveSmallIntegerField(default=1)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Spell Reward',
                'verbose_name_plural': 'Spell Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TitleReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('title_text', models.CharField(max_length=200)),
                ('is_prefix', models.BooleanField(default=True, help_text='Is this a prefix or suffix title')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Title Reward',
                'verbose_name_plural': 'Title Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('charges', models.PositiveIntegerField(blank=True, help_text='Number of charges, if applicable', null=True)),
                ('attuned', models.BooleanField(default=False, help_text='Whether the item is attuned (no-trade)')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Item Reward',
                'verbose_name_plural': 'Item Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
                'indexes': [models.Index(fields=['item_id'], name='reward_item_id_idx'), models.Index(fields=['item_name'], name='reward_item_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactionReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('faction_id', models.IntegerField()),
                ('faction_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(help_text='Positive for faction gain, negative for faction loss')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Faction Reward',
                'verbose_name_plural': 'Faction Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
                'indexes': [models.Index(fields=['faction_id'], name='reward_faction_id_idx'), models.Index(fields=['faction_name'], name='reward_faction_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether player can choose this reward or not')),
                ('reward_group', models.PositiveSmallIntegerField(default=0, help_text='Group rewards together - player chooses one reward from each group')),
                ('flag_name', models.CharField(max_length=100)),
                ('flag_value', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='What access does this flag provide?')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rewards', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Access Reward',
                'verbose_name_plural': 'Access Rewards',
                'ordering': ['quest', 'reward_group'],
                'abstract': False,
                'indexes': [models.Index(fields=['flag_name'], name='reward_flag_name_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quests',
            index=models.Index(fields=['name'], name='quest_name_idx'),
        ),
        migrations.AddIndex(
            model_name='quests',
            index=models.Index(fields=['starting_zone'], name='starting_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='quests',
            index=models.Index(fields=['starting_npc_id'], name='starting_npc_idx'),
        ),
        migrations.AddIndex(
            model_name='quests',
            index=models.Index(fields=['expansion_introduced'], name='expansion_idx'),
        ),
        migrations.AddIndex(
            model_name='quests',
            index=models.Index(fields=['minimum_level', 'maximum_level'], name='level_range_idx'),
        ),
        migrations.AddIndex(
            model_name='quests',
            index=models.Index(fields=['class_restrictions'], name='class_idx'),
        ),
        migrations.AddIndex(
            model_name='quests',
            index=models.Index(fields=['race_restrictions'], name='race_idx'),
        ),
        migrations.AddIndex(
            model_name='spellreward',
            index=models.Index(fields=['spell_id'], name='reward_spell_id_idx'),
        ),
    ]
