# Generated by Django 5.2.12 on 2026-04-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '__first__'),
        ('quests', '0003_create_missing_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestPatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('introduced', 'Introduced'), ('updated', 'Updated')], default='updated', max_length=10)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_history', to='patch.patchmessage')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_history', to='quests.quests')),
            ],
            options={
                'verbose_name': 'Quest Patch History',
                'verbose_name_plural': 'Quest Patch Histories',
                'ordering': ['patch__patch_date'],
                'unique_together': {('quest', 'patch', 'role')},
            },
        ),
    ]
