# Generated by Django 5.2.12 on 2026-04-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_add_quest_patch_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10),
        ),
    ]
