# Generated by Django 5.1.4 on 2026-03-22 03:53

from django.db import migrations


CATEGORIES = [
    {
        'name': 'Bug Report',
        'description': 'Report a bug, broken quest, or unexpected game behavior',
        'icon': 'fas fa-bug',
        'order': 10,
    },
    {
        'name': 'Stuck / Corpse Retrieval',
        'description': 'Character is stuck or you need help recovering a corpse',
        'icon': 'fas fa-skull-crossbones',
        'order': 20,
    },
    {
        'name': 'Item / Currency Issue',
        'description': 'Missing items, wrong loot, merchant error, or lost currency',
        'icon': 'fas fa-coins',
        'order': 30,
    },
    {
        'name': 'Harassment / Code of Conduct',
        'description': 'Report player harassment, cheating, or rule violations',
        'icon': 'fas fa-shield-alt',
        'order': 40,
    },
    {
        'name': 'Account Help',
        'description': 'Login issues, account access problems, or password recovery',
        'icon': 'fas fa-user-lock',
        'order': 50,
    },
    {
        'name': 'Appeal / Dispute',
        'description': 'Appeal a ban, suspension, or staff decision',
        'icon': 'fas fa-gavel',
        'order': 60,
    },
    {
        'name': 'Other',
        'description': 'General questions or issues not covered by another category',
        'icon': 'fas fa-question-circle',
        'order': 70,
    },
]


def seed_categories(apps, schema_editor):
    PetitionCategory = apps.get_model('petitions', 'PetitionCategory')
    for cat in CATEGORIES:
        PetitionCategory.objects.get_or_create(name=cat['name'], defaults=cat)


def unseed_categories(apps, schema_editor):
    PetitionCategory = apps.get_model('petitions', 'PetitionCategory')
    names = [c['name'] for c in CATEGORIES]
    PetitionCategory.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
