# Generated by Django 5.1.4 on 2026-03-22 00:27

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('charname', models.CharField(max_length=64)),
                ('sharedplat', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('lsaccount_id', models.IntegerField(default=None, unique=True)),
                ('forum_id', models.IntegerField(default=0)),
                ('gmspeed', models.SmallIntegerField(default=0)),
                ('revoked', models.SmallIntegerField(default=0)),
                ('karma', models.IntegerField(default=0)),
                ('minilogin_ip', models.CharField(max_length=32)),
                ('hideme', models.SmallIntegerField(default=0)),
                ('rulesflag', models.SmallIntegerField(default=0)),
                ('suspendeduntil', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('time_creation', models.IntegerField(default=0)),
                ('expansion', models.SmallIntegerField(default=12)),
                ('ban_reason', models.TextField(blank=True, default=None, null=True)),
                ('suspend_reason', models.TextField(blank=True, default=None, null=True)),
                ('active', models.SmallIntegerField(default=0)),
                ('ip_exemption_multiplier', models.IntegerField(default=1, null=True)),
                ('gminvul', models.SmallIntegerField(default=0)),
                ('flymode', models.SmallIntegerField(default=0)),
                ('ignore_tells', models.SmallIntegerField(default=0)),
                ('mule', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginServerAccounts',
            fields=[
                ('AccountCreateDate', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('LoginServerID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=30, unique=True)),
                ('AccountPassword', models.CharField(max_length=50)),
                ('AccountEmail', models.EmailField(max_length=100)),
                ('LastLoginDate', models.DateField(default=django.utils.timezone.now)),
                ('LastIPAddress', models.GenericIPAddressField()),
                ('created_by', models.IntegerField(default=0)),
                ('client_unlock', models.SmallIntegerField()),
                ('creationIP', models.GenericIPAddressField()),
                ('ForumName', models.CharField(max_length=30)),
                ('max_accts', models.SmallIntegerField()),
                ('Num_IP_Bypass', models.SmallIntegerField(null=True)),
                ('lastpass_change', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Login Server Accounts',
                'db_table': 'tblLoginServerAccounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerAdminRegistration',
            fields=[
                ('ServerAdminID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=30)),
                ('AccountPassword', models.CharField(max_length=30)),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('RegistrationDate', models.DateTimeField()),
                ('RegistrationIPAddr', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name_plural': 'Server Admin Registrations',
                'db_table': 'tblServerAdminRegistration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerListType',
            fields=[
                ('ServerListTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('ServerListTypeDescription', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Server List Types',
                'db_table': 'tblServerListType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorldServerRegistration',
            fields=[
                ('ServerID', models.AutoField(primary_key=True, serialize=False)),
                ('ServerLongName', models.CharField(max_length=100)),
                ('ServerTagDescription', models.CharField(max_length=50)),
                ('ServerShortName', models.CharField(max_length=25)),
                ('ServerListTypeID', models.IntegerField(default=3)),
                ('ServerLastLoginDate', models.DateField(null=True)),
                ('ServerLastIPAddr', models.GenericIPAddressField(null=True)),
                ('ServerAdminID', models.IntegerField()),
                ('ServerTrusted', models.IntegerField()),
                ('Note', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'World Server Registrations',
                'db_table': 'tblWorldServerRegistration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
