# Generated by Django 4.2.5 on 2023-09-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginServerAccounts',
            fields=[
                ('AccountCreateDate', models.DateTimeField(auto_created=True)),
                ('LoginServerID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=30)),
                ('AccountPassword', models.CharField(max_length=50)),
                ('AccountEmail', models.EmailField(max_length=100)),
                ('LastLoginDate', models.DateField()),
                ('LastIPAddress', models.GenericIPAddressField()),
                ('created_by', models.IntegerField()),
                ('client_unlock', models.SmallIntegerField()),
                ('creationIP', models.GenericIPAddressField()),
                ('ForumName', models.CharField(max_length=30)),
                ('max_accts', models.SmallIntegerField()),
                ('Num_IP_Bypass', models.SmallIntegerField(null=True)),
                ('lastpass_change', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Login Server Accounts',
                'db_table': 'tblLoginServerAccounts',
            },
        ),
        migrations.CreateModel(
            name='ServerAdminRegistration',
            fields=[
                ('ServerAdminID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountName', models.CharField(max_length=30)),
                ('AccountPassword', models.CharField(max_length=30)),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('RegistrationDate', models.DateTimeField()),
                ('RegistrationIPAddr', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name_plural': 'Server Admin Registrations',
                'db_table': 'tblServerAdminRegistration',
            },
        ),
        migrations.CreateModel(
            name='ServerListType',
            fields=[
                ('ServerListTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('ServerListTypeDescription', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Server List Types',
                'db_table': 'tblServerListType',
            },
        ),
        migrations.CreateModel(
            name='WorldServerRegistration',
            fields=[
                ('ServerID', models.AutoField(primary_key=True, serialize=False)),
                ('ServerLongName', models.CharField(max_length=100)),
                ('ServerTagDescription', models.CharField(max_length=50)),
                ('ServerShortName', models.CharField(max_length=25)),
                ('ServerListTypeID', models.IntegerField(default=3)),
                ('ServerLastLoginDate', models.DateField(null=True)),
                ('ServerLastIPAddr', models.GenericIPAddressField(null=True)),
                ('ServerAdminID', models.IntegerField()),
                ('ServerTrusted', models.IntegerField()),
                ('Note', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'World Server Registrations',
                'db_table': 'tblWorldServerRegistration',
            },
        ),
    ]
