# Generated by Django 4.2.5 on 2023-10-09 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('charname', models.CharField(max_length=64)),
                ('sharedplat', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('lsaccount_id', models.IntegerField(default=None, unique=True)),
                ('forum_id', models.IntegerField(default=0)),
                ('gmspeed', models.SmallIntegerField(default=0)),
                ('revoked', models.SmallIntegerField(default=0)),
                ('karma', models.IntegerField(default=0)),
                ('minilogin_ip', models.CharField(max_length=32)),
                ('hideme', models.SmallIntegerField(default=0)),
                ('rulesflag', models.SmallIntegerField(default=0)),
                ('suspendeduntil', models.DateTimeField(default='0000-00-00 00:00:00')),
                ('time_creation', models.IntegerField(default=0)),
                ('expansion', models.SmallIntegerField(default=12)),
                ('ban_reason', models.TextField(default=None, null=True)),
                ('suspend_reason', models.TextField(default=None, null=True)),
                ('active', models.SmallIntegerField(default=0)),
                ('ip_exemption_multiplier', models.IntegerField(default=1, null=True)),
                ('gminvul', models.SmallIntegerField(default=0)),
                ('flymode', models.SmallIntegerField(default=0)),
                ('ignore_tells', models.SmallIntegerField(default=0)),
                ('mule', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.AlterField(
            model_name='loginserveraccounts',
            name='AccountCreateDate',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginserveraccounts',
            name='LastLoginDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginserveraccounts',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
    ]
