# Generated by Django 5.2.12 on 2026-04-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False, 'permissions': [('can_suspend_accounts', 'Can suspend and lift player game accounts')]},
        ),
    ]
