# Generated by Django 4.2.5 on 2023-10-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_alter_loginserveraccounts_accountcreatedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginserveraccounts',
            name='AccountName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
