# Generated by Django 5.1.4 on 2026-03-22 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dkp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RaidEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive name for this raid, e.g. "Tuesday NToV Progression"', max_length=150)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('circuit_name', models.CharField(blank=True, help_text='Free-text circuit name when not linked to an existing circuit', max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('posted_by_name', models.CharField(blank=True, help_text='Display name override for the poster. Leave blank to use their account username.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raid_events', to='dkp.raidcircuit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_raid_events', to=settings.AUTH_USER_MODEL)),
                ('targets', models.ManyToManyField(blank=True, related_name='raid_events', to='raid_scheduler.raidtarget')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='GMOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_overrides', to='raid_scheduler.raidevent')),
            ],
        ),
        migrations.CreateModel(
            name='RaidSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Name for invites not linked to a roster member', max_length=100)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('declined', 'Declined')], default='confirmed', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='raid_scheduler.raidevent')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raid_signups', to='dkp.circuitmembership')),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
    ]
