# Generated by Django 5.2.12 on 2026-04-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raid_scheduler', '0003_raidevent_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidevent',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='raidevent',
            name='timezone',
            field=models.CharField(choices=[('North America', [('America/New_York', 'Eastern Time (ET)'), ('America/Chicago', 'Central Time (CT)'), ('America/Denver', 'Mountain Time (MT)'), ('America/Los_Angeles', 'Pacific Time (PT)'), ('America/Anchorage', 'Alaska Time (AKT)'), ('Pacific/Honolulu', 'Hawaii Time (HT)')]), ('Europe', [('Europe/London', 'London (GMT/BST)'), ('Europe/Paris', 'Paris / Berlin / Rome (CET/CEST)'), ('Europe/Helsinki', 'Helsinki / Athens (EET/EEST)'), ('Europe/Moscow', 'Moscow (MSK)')])], default='America/New_York', max_length=50),
        ),
    ]
