# Generated by Django 5.1.4 on 2026-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BISEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.SmallIntegerField()),
                ('expansion', models.CharField(choices=[('vanilla-pre-planar', 'Classic: Pre-Planar'), ('vanilla-planar', 'Classic: Planar'), ('kunark', 'Kunark'), ('velious-group', 'Velious: Group'), ('velious-raid', 'Velious: Raid'), ('luclin-group', 'Luclin: Group'), ('luclin-raid', 'Luclin: Raid'), ('pop-group', 'Planes of Power: Group'), ('pop-raid', 'Planes of Power: Raid')], max_length=32)),
                ('slot', models.CharField(max_length=48)),
                ('item_name', models.CharField(max_length=128)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'BIS Entry',
                'verbose_name_plural': 'BIS Entries',
                'ordering': ['slot', 'rank'],
                'unique_together': {('class_id', 'expansion', 'slot', 'item_name')},
            },
        ),
    ]
