# Generated by Django 5.1.4 on 2026-03-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BISRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.SmallIntegerField()),
                ('expansion', models.CharField(max_length=32)),
                ('slot', models.CharField(max_length=48)),
                ('item_name', models.CharField(max_length=128)),
                ('action', models.CharField(choices=[('add', 'Added'), ('remove', 'Removed'), ('reorder', 'Reordered'), ('edit', 'Edited')], max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('old_note', models.CharField(blank=True, max_length=150)),
                ('new_note', models.CharField(blank=True, max_length=150)),
                ('edit_summary', models.CharField(blank=True, max_length=200)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
