# Generated by Django 5.2.12 on 2026-03-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemexpansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemexpansion',
            name='expansion',
            field=models.IntegerField(choices=[(0, 'Original EverQuest'), (1, 'Ruins of Kunark'), (2, 'Scars of Velious'), (3, 'Shadows of Luclin'), (4, 'Planes of Power'), (5, 'Legacy of Ykesha'), (6, 'Lost Dungeons of Norrath'), (7, 'Gates of Discord'), (8, 'Omens of War'), (9, 'Dragons of Norrath'), (10, 'Depths of Darkhollow'), (11, 'Prophecy of Ro'), (12, "The Serpent's Spine"), (13, 'The Buried Sea'), (14, 'Secrets of Faydwer'), (15, 'Seeds of Destruction'), (16, 'Underfoot'), (17, 'House of Thule'), (18, 'Veil of Alaris'), (19, 'Rain of Fear'), (20, 'Call of the Forsaken'), (21, 'The Darkened Sea'), (22, 'The Broken Mirror'), (23, 'Empires of Kunark'), (24, 'Ring of Scale'), (25, 'The Burning Lands'), (26, 'Torment of Velious'), (27, 'Claws of Veeshan'), (28, 'Terror of Luclin'), (29, 'Night of Shadows'), (30, "Laurion's Song"), (31, 'The Outer Brood')], db_index=True),
        ),
    ]
