# Generated by Django 5.2.12 on 2026-04-02 16:04

import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body_markdown', models.TextField()),
                ('body_plaintext', models.TextField(blank=True, null=True)),
                ('patch_date', models.DateTimeField()),
                ('patch_number_this_date', models.IntegerField(default=1)),
                ('patch_year', models.IntegerField(default=1999)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', mdeditor.fields.MDTextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='patch.comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('patch_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='patch.patchmessage')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
