# Generated by Django 5.2.12 on 2026-04-05 17:23

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchmessage',
            name='body_markdown',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AddIndex(
            model_name='patchmessage',
            index=models.Index(fields=['patch_year'], name='patch_patch_patch_y_26a82d_idx'),
        ),
        migrations.AddIndex(
            model_name='patchmessage',
            index=models.Index(fields=['patch_date'], name='patch_patch_patch_d_e43f68_idx'),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE patch_patchmessage ADD FULLTEXT INDEX patch_patchmessage_fulltext (title, body_plaintext)',
            reverse_sql='ALTER TABLE patch_patchmessage DROP INDEX patch_patchmessage_fulltext',
        ),
    ]
