# Generated by Django 5.2.12 on 2026-04-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0002_body_markdown_mdfield_add_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE patch_patchmessage DROP INDEX patch_patchmessage_fulltext',
            reverse_sql='ALTER TABLE patch_patchmessage ADD FULLTEXT INDEX patch_patchmessage_fulltext (title, body_plaintext)',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE patch_patchmessage ADD FULLTEXT INDEX patch_patchmessage_fulltext (title, body_plaintext, body_markdown)',
            reverse_sql='ALTER TABLE patch_patchmessage DROP INDEX patch_patchmessage_fulltext',
        ),
    ]
