# Generated by Django 5.2.12 on 2026-04-05 17:49

import re
from datetime import date
from django.db import migrations, models

_HOTFIX_RE = re.compile(r'hot\s*fix', re.IGNORECASE)
_PRESS_RE = re.compile(r'press release', re.IGNORECASE)
_NEWS_RE = re.compile(r'news bit|terrorist attack|follow.up|news story', re.IGNORECASE)


def _classify_type(title):
    if _HOTFIX_RE.search(title):
        return 'hotfix'
    if _PRESS_RE.search(title):
        return 'press_release'
    if _NEWS_RE.search(title):
        return 'news'
    return 'patch'


def _get_expansion(patch_date):
    if not patch_date:
        return None
    d = patch_date.date()
    if d < date(2000, 4, 24):  return 'classic'
    if d < date(2000, 12, 5):  return 'kunark'
    if d < date(2001, 12, 4):  return 'velious'
    if d < date(2002, 10, 22): return 'luclin'
    if d < date(2003, 2, 10):  return 'pop'
    if d < date(2003, 9, 9):   return 'ykesha'
    if d < date(2004, 2, 10):  return 'ldon'
    if d < date(2004, 9, 14):  return 'gates'
    if d < date(2005, 2, 15):  return 'omens'
    if d < date(2005, 9, 13):  return 'dragons'
    if d < date(2006, 2, 21):  return 'dod'
    if d < date(2006, 9, 19):  return 'por'
    if d < date(2007, 2, 13):  return 'tss'
    if d < date(2007, 11, 13): return 'tbs'
    if d < date(2008, 10, 21): return 'sof'
    if d < date(2009, 12, 15): return 'sod'
    if d < date(2010, 10, 12): return 'underfoot'
    return 'hot'


def populate_fields(apps, schema_editor):
    PatchMessage = apps.get_model('patch', 'PatchMessage')
    for pm in PatchMessage.objects.all():
        pm.patch_type = _classify_type(pm.title)
        pm.expansion = _get_expansion(pm.patch_date)
        pm.source_notes = 'Combined EverQuest live server patch archive, 1999–2010'
        pm.save(update_fields=['patch_type', 'expansion', 'source_notes'])


def depopulate_fields(apps, schema_editor):
    PatchMessage = apps.get_model('patch', 'PatchMessage')
    PatchMessage.objects.all().update(patch_type='patch', expansion=None, source_notes=None)


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0003_update_fulltext_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchmessage',
            name='expansion',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('kunark', 'Ruins of Kunark'), ('velious', 'Scars of Velious'), ('luclin', 'Shadows of Luclin'), ('pop', 'Planes of Power'), ('ykesha', 'Legacy of Ykesha'), ('ldon', 'Lost Dungeons of Norrath'), ('gates', 'Gates of Discord'), ('omens', 'Omens of War'), ('dragons', 'Dragons of Norrath'), ('dod', 'Depths of Darkhollow'), ('por', 'Prophecy of Ro'), ('tss', "The Serpent's Spine"), ('tbs', 'The Buried Sea'), ('sof', 'Secrets of Faydwer'), ('sod', 'Seeds of Destruction'), ('underfoot', 'Underfoot'), ('hot', 'House of Thule')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patchmessage',
            name='markdown_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patchmessage',
            name='patch_type',
            field=models.CharField(choices=[('patch', 'Patch'), ('hotfix', 'Hotfix'), ('press_release', 'Press Release'), ('news', 'News')], default='patch', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(populate_fields, depopulate_fields),
    ]
