# Generated by Django 5.2.12 on 2026-04-05 18:01

import re
from django.db import migrations, models

PATCH_TAGS = [
    ('bugfix',        'Bug Fixes'),
    ('content',       'New Content'),
    ('class_changes', 'Class Changes'),
    ('spells',        'Spells'),
    ('items',         'Items'),
    ('zones',         'Zones'),
    ('tradeskills',   'Tradeskills'),
    ('pvp',           'PvP'),
    ('ui',            'UI'),
    ('server',        'Server Infrastructure'),
]

TAG_PATTERNS = {
    'bugfix':        re.compile(r'\b(bug|fixed?|corrected?|crash)\b', re.IGNORECASE),
    'content':       re.compile(r'\b(new zone|new spell|new item|new quest|new npc|new area)\b', re.IGNORECASE),
    'class_changes': re.compile(r'\b(warrior|monk|paladin|shadow knight|druid|cleric|shaman|bard|rogue|wizard|magician|enchanter|necromancer|ranger|beastlord|berserker)\b', re.IGNORECASE),
    'spells':        re.compile(r'\b(spell|resist|mana)\b', re.IGNORECASE),
    'items':         re.compile(r'\b(item|loot|weapon|armor|container)\b', re.IGNORECASE),
    'zones':         re.compile(r'\b(zone|dungeon|instance)\b', re.IGNORECASE),
    'tradeskills':   re.compile(r'\b(tradeskill|smithing|tailoring|pottery|brewing|fletching|baking|jewelry|research)\b', re.IGNORECASE),
    'pvp':           re.compile(r'\b(pvp|player vs player)\b', re.IGNORECASE),
    'ui':            re.compile(r'\b(interface|ui|hotkey|chat command)\b', re.IGNORECASE),
    'server':        re.compile(r'\b(server|downtime|maintenance|restart)\b', re.IGNORECASE),
}


def create_tags_and_autotag(apps, schema_editor):
    PatchMessage = apps.get_model('patch', 'PatchMessage')
    PatchTag = apps.get_model('patch', 'PatchTag')

    # Create the 10 PatchTag records
    tags_by_slug = {}
    for slug, name in PATCH_TAGS:
        tag, _ = PatchTag.objects.get_or_create(slug=slug, defaults={'name': name})
        tags_by_slug[slug] = tag

    # Auto-tag every PatchMessage
    for pm in PatchMessage.objects.all():
        text = pm.body_plaintext or ''
        for tag_slug, pattern in TAG_PATTERNS.items():
            if pattern.search(text):
                pm.tags.add(tags_by_slug[tag_slug])


def remove_tags(apps, schema_editor):
    PatchTag = apps.get_model('patch', 'PatchTag')
    PatchTag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0005_fix_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='patchmessage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='patches', to='patch.patchtag'),
        ),
        migrations.RunPython(create_tags_and_autotag, remove_tags),
    ]
