RACES = {
    0: 'Doug',
    1: 'Human',
    2: 'Barbarian',
    3: 'Erudite',
    4: 'Wood Elf',
    5: 'High Elf',
    6: 'Dark Elf',
    7: 'Half Elf',
    8: 'Dwarf',
    9: 'Troll',
    10: 'Ogre',
    11: 'Halfling',
    12: 'Gnome',
    13: 'Aviak',
    14: 'Werewolf',
    15: 'Brownie',
    16: 'Centaur',
    17: 'Golem',
    18: 'Giant/Cyclops',
    19: 'Trakanon',
    20: 'Doppleganger',
    21: 'Evil Eye',
    22: 'Beetle',
    23: 'Kerran',
    24: 'Fish',
    25: 'Fairy',
    26: 'Froglok',
    27: 'Froglok Ghoul',
    28: 'Fungusman',
    29: 'Gargoyle',
    30: 'Gasbag',
    31: 'Gelatinous Cube',
    32: 'Ghost',
    33: 'Ghoul',
    34: 'Giant Bat',
    35: 'Giant Eel',
    36: 'Giant Rat',
    37: 'Giant Snake',
    38: 'Giant Spider',
    39: 'Gnoll',
    40: 'Goblin',
    41: 'Gorilla',
    42: 'Wolf',
    43: 'Bear',
    44: 'Freeport Guard',
    45: 'Demi Lich',
    46: 'Imp',
    47: 'Griffin',
    48: 'Kobold',
    49: 'Lava Dragon',
    50: 'Lion',
    51: 'Lizard Man',
    52: 'Mimic',
    53: 'Minotaur',
    54: 'Orc',
    55: 'Human Beggar',
    56: 'Pixie',
    57: 'Dracnid',
    58: 'Solusek Ro',
    59: 'Bloodgill',
    60: 'Skeleton',
    61: 'Shark',
    62: 'Tunare',
    63: 'Tiger',
    64: 'Treant',
    65: 'Vampire',
    66: 'Statue of Rallos Zek',
    67: 'Highpass Citizen',
    68: 'Tentacle',
    69: 'Wisp',
    70: 'Zombie',
    71: 'Qeynos Citizen',
    72: 'Ship',
    73: 'Launch',
    74: 'Piranha',
    75: 'Elemental',
    76: 'Puma',
    77: 'Neriak Citizen',
    78: 'Erudite Citizen',
    79: 'Bixie',
    80: 'Reanimated Hand',
    81: 'Rivervale Citizen',
    82: 'Scarecrow',
    83: 'Skunk',
    84: 'Snake Elemental',
    85: 'Spectre',
    86: 'Sphinx',
    87: 'Armadillo',
    88: 'Clockwork Gnome',
    89: 'Drake',
    90: 'Halas Citizen',
    91: 'Alligator',
    92: 'Grobb Citizen',
    93: 'Oggok Citizen',
    94: 'Kaladim Citizen',
    95: 'Cazic Thule',
    96: 'Cockatrice',
    97: 'Daisy Man',
    98: 'Elf Vampire',
    99: 'Denizen',
    100: 'Dervish',
    101: 'Efreeti',
    102: 'Froglok Tadpole',
    103: 'Phinigel Autropos',
    104: 'Leech',
    105: 'Swordfish',
    106: 'Felguard',
    107: 'Mammoth',
    108: 'Eye of Zomm',
    109: 'Wasp',
    110: 'Mermaid',
    111: 'Harpie',
    112: 'Fayguard',
    113: 'Drixie',
    114: 'Ghost Ship',
    115: 'Clam',
    116: 'Sea Horse',
    117: 'Dwarf Ghost',
    118: 'Erudite Ghost',
    119: 'Sabertooth',
    120: 'Wolf Elemental',
    121: 'Gorgon',
    122: 'Dragon Skeleton',
    123: 'Innoruuk',
    124: 'Unicorn',
    125: 'Pegasus',
    126: 'Djinn',
    127: 'Invisible Man',
    128: 'Iksar',
    129: 'Scorpion',
    130: 'Vah Shir',
    131: 'Sarnak',
    132: 'Draglock',
    133: 'Lycanthrope',
    134: 'Mosquito',
    135: 'Rhino',
    136: 'Xalgoz',
    137: 'Kunark Goblin',
    138: 'Yeti',
    139: 'Iksar Citizen',
    140: 'Forest Giant',
    141: 'Boat',
    142: 'Minor Illusion',
    143: 'Tree Illusion',
    144: 'Burynai',
    145: 'Goo',
    146: 'Spectral Sarnak',
    147: 'Spectral Iksar',
    148: 'Kunark Fish',
    149: 'Iksar Scorpion',
    150: 'Erollisi',
    151: 'Tribunal',
    152: 'Bertoxxulous',
    153: 'Bristlebane',
    154: 'Fay Drake',
    155: 'Sarnak Skeleton',
    156: 'Ratman',
    157: 'Wyvern',
    158: 'Wurm',
    159: 'Devourer',
    160: 'Iksar Golem',
    161: 'Iksar Skeleton',
    162: 'Man Eating Plant',
    163: 'Raptor',
    164: 'Sarnak Golem',
    165: 'Water Dragon',
    166: 'Iksar Hand',
    167: 'Succulent',
    168: 'Holgresh',
    169: 'Brontotherium',
    170: 'Snow Dervish',
    171: 'Dire Wolf',
    172: 'Manticore',
    173: 'Totem',
    174: 'Cold Spectre',
    175: 'Enchanted Armor',
    176: 'Snow Bunny',
    177: 'Walrus',
    178: 'Rock-gem Man',
    179: 'Unknown179',
    180: 'Unknown180',
    181: 'Yak Man',
    182: 'Faun',
    183: 'Coldain',
    184: 'Velious Dragon',
    185: 'Hag',
    186: 'Hippogriff',
    187: 'Siren',
    188: 'Frost Giant',
    189: 'Storm Giant',
    190: 'Otterman',
    191: 'Walrus Man',
    192: 'Clockwork Dragon',
    193: 'Abhorrent',
    194: 'Sea Turtle',
    195: 'Black and White Dragon',
    196: 'Ghost Dragon',
    197: 'Ronnie Test',
    198: 'Prismatic Dragon',
    199: 'Shiknar',
    200: 'Rockhopper',
    201: 'Underbulk',
    202: 'Grimling',
    203: 'Vacuum Worm',
    204: 'Evan Test',
    205: 'Kahli Shah',
    206: 'Owlbear',
    207: 'Rhino Beetle',
    208: 'Vampyre',
    209: 'Earth Elemental',
    210: 'Air Elemental',
    211: 'Water Elemental',
    212: 'Fire Elemental',
    213: 'Wetfang Minnow',
    214: 'Thought Horror',
    215: 'Tegi',
    216: 'Horse',
    217: 'Shissar',
    218: 'Fungal Fiend',
    219: 'Vampire Volatalis',
    220: 'StoneGrabber',
    221: 'Scarlet Cheetah',
    222: 'Zelniak',
    223: 'Lightcrawler',
    224: 'Shade',
    225: 'Sunflower',
    226: 'Khati Sha',
    227: 'Shrieker',
    228: 'Galorian',
    229: 'Netherbian',
    230: 'Akhevan',
    231: 'Spire Spirit',
    232: 'Sonic Wolf',
    233: 'Ground Shaker',
    234: 'Vah Shir Skeleton',
    235: 'Mutant Humanoid',
    236: 'Lord Inquisitor Seru',
    237: 'Recuso',
    238: 'Vah Shir King',
    239: 'Vah Shir Guard',
    240: 'Teleport Man',
    241: 'Lujein',
    242: 'Naiad',
    243: 'Nymph',
    244: 'Ent',
    245: 'Wrinnfly',
    246: 'Coirnav',
    247: 'Solusek Ro',
    248: 'Clockwork Golem',
    249: 'Clockwork Brain',
    250: 'Spectral Banshee',
    251: 'Guard of Justice',
    252: 'PoM Castle',
    253: 'Disease Boss',
    254: 'Solusek Ro Guard',
    255: 'Bertoxxulous (New)',
    256: 'Tribunal (New)',
    257: 'Terris Thule',
    258: 'Vegerog',
    259: 'Crocodile',
    260: 'Bat',
    261: 'Slarghilug',
    262: 'Tranquilion',
    263: 'Tin Soldier',
    264: 'Nightmare Wraith',
    265: 'Malarian',
    266: 'Knight of Pestilence',
    267: 'Lepertoloth',
    268: 'Bubonian Boss',
    269: 'Bubonian Underling',
    270: 'Pusling',
    271: 'Water Mephit',
    272: 'Stormrider',
    273: 'Junk Beast',
    274: 'Broken Clockwork',
    275: 'Giant Clockwork',
    276: 'Clockwork Beetle',
    277: 'Nightmare Goblin',
    278: 'Karana',
    279: 'Blood Raven',
    280: 'Nightmare Gargoyle',
    281: 'Mouth of Insanity',
    282: 'Skeletal Horse',
    283: 'Saryrn',
    284: 'Fennin Ro',
    285: 'Tormentor',
    286: 'Necromancer Priest',
    287: 'Nightmare',
    288: 'New Rallos Zek',
    289: 'Vallon Zek',
    290: 'Tallon Zek',
    291: 'Air Mephit',
    292: 'Earth Mephit',
    293: 'Fire Mephit',
    294: 'Nightmare Mephit',
    295: 'Zebuxoruk',
    296: 'Mithaniel Marr',
    297: 'Knightmare Rider',
    298: 'Rathe Councilman',
    299: 'Xegony',
    300: 'Demon/Fiend',
    301: 'Test Object',
    302: 'Lobster Monster',
    303: 'Phoenix',
    304: 'Quarm',
    305: 'New Bear',
    306: 'Earth Golem',
    307: 'Iron Golem',
    308: 'Storm Golem',
    309: 'Air Golem',
    310: 'Wood Golem',
    311: 'Fire Golem',
    312: 'Water Golem',
    313: 'Veiled Gargoyle',
    314: 'Lynx',
    315: 'Squid',
    316: 'Frog',
    317: 'Flying Serpent',
    318: 'Tactics Soldier',
    319: 'Armored Boar',
    320: 'Djinni',
    321: 'Boar',
    322: 'Knight of Marr',
    323: 'Armor of Marr',
    324: 'Nightmare Knight',
    325: 'Rallos Ogre',
    326: 'Arachnid',
    327: 'Crystal Arachnid',
    328: 'Tower Model',
    329: 'Portal'
}

PET_CLASSES = {
    2: "Cleric",
    5: "Shadow Knight",
    6: "Druid",
    10: "Shaman",
    11: "Necromancer",
    12: "Wizard",
    13: "Magician",
    14: "Enchanter",
    15: "Beastlord"
}


ZONE_SHORT_TO_LONG = {
    "qeynos": "South Qeynos",
    "qeynos2": "North Qeynos",
    "qrg": "The Surefall Glade",
    "qeytoqrg": "The Qeynos Hills",
    "highpass": "Highpass Hold",
    "highkeep": "High Keep",
    "Unused": "Unused",
    "freportn": "North Freeport",
    "freportw": "West Freeport",
    "freporte": "East Freeport",
    "runnyeye": "The Liberated Citadel of Runnyeye",
    "qey2hh1": "The Western Plains of Karana",
    "northkarana": "The Northern Plains of Karana",
    "southkarana": "The Southern Plains of Karana",
    "eastkarana": "Eastern Plains of Karana",
    "beholder": "Gorge of King Xorbb",
    "blackburrow": "Blackburrow",
    "paw": "The Lair of the Splitpaw",
    "rivervale": "Rivervale",
    "kithicor": "Kithicor Forest",
    "commons": "West Commonlands",
    "ecommons": "East Commonlands",
    "erudnint": "The Erudin Palace",
    "erudnext": "Erudin",
    "nektulos": "The Nektulos Forest",
    "cshome": "Sunset Home",
    "lavastorm": "The Lavastorm Mountains",
    "nektropos": "Nektropos",
    "halas": "Halas",
    "everfrost": "Everfrost Peaks",
    "soldunga": "Solusek's Eye",
    "soldungb": "Nagafen's Lair",
    "misty": "Misty Thicket",
    "nro": "Northern Desert of Ro",
    "sro": "Southern Desert of Ro",
    "befallen": "Befallen",
    "oasis": "Oasis of Marr",
    "tox": "Toxxulia Forest",
    "hole": "The Hole",
    "neriaka": "Neriak - Foreign Quarter",
    "neriakb": "Neriak - Commons",
    "neriakc": "Neriak - 3rd Gate",
    "neriakd": "Neriak Palace",
    "najena": "Najena",
    "qcat": "The Qeynos Aqueduct System",
    "innothule": "Innothule Swamp",
    "feerrott": "The Feerott",
    "cazicthule": "Accursed Temple of CazicThule",
    "oggok": "Oggok",
    "rathemtn": "The Rathe Mountains",
    "lakerathe": "Lake Rathetear",
    "grobb": "Grobb",
    "aviak": "Aviak Village",
    "gfaydark": "The Greater Faydark",
    "akanon": "Ak'Anon",
    "steamfont": "Steamfont Mountains",
    "lfaydark": "The Lesser Faydark",
    "crushbone": "Crushbone",
    "mistmoore": "The Castle of Mistmoore",
    "kaladima": "South Kaladim",
    "felwithea": "Northern Felwithe",
    "felwitheb": "Southern Felwithe",
    "unrest": "The Estate of Unrest",
    "kedge": "Kedge Keep",
    "guktop": "The City of Guk",
    "gukbottom": "The Ruins of Old Guk",
    "kaladimb": "North Kaladim",
    "butcher": "Butcherblock Mountains",
    "oot": "Ocean of Tears",
    "cauldron": "Dagnor's Cauldron",
    "airplane": "The Plane of Sky",
    "fearplane": "The Plane of Fear",
    "permafrost": "The Permafrost Caverns",
    "kerraridge": "Kerra Isle",
    "paineel": "Paineel",
    "hateplane": "Plane of Hate",
    "arena": "The Arena",
    "fieldofbone": "The Field of Bone",
    "warslikswood": "The Warsliks Woods",
    "soltemple": "The Temple of Solusek Ro",
    "droga": "The Temple of Droga",
    "cabwest": "Cabilis West",
    "swampofnohope": "The Swamp of No Hope",
    "firiona": "Firiona Vie",
    "lakeofillomen": "Lake of Ill Omen",
    "dreadlands": "The Dreadlands",
    "burningwood": "The Burning Wood",
    "kaesora": "Kaesora",
    "sebilis": "The Ruins of Sebilis",
    "citymist": "The City of Mist",
    "skyfire": "The Skyfire Mountains",
    "frontiermtns": "Frontier Mountains",
    "overthere": "The Overthere",
    "emeraldjungle": "The Emerald Jungle",
    "trakanon": "Trakanon's Teeth",
    "timorous": "Timorous Deep",
    "kurn": "Kurn's Tower",
    "erudsxing": "Erud's Crossing",
    "unused": "Unused",
    "stonebrunt": "The Stonebrunt Mountains",
    "warrens": "The Warrens",
    "karnor": "Karnor's Castle",
    "chardok": "Chardok",
    "dalnir": "The Crypt of Dalnir",
    "charasis": "The Howling Stones",
    "cabeast": "Cabilis East",
    "nurga": "The Mines of Nurga",
    "veeshan": "Veeshan's Peak",
    "veksar": "Veksar",
}

SPELL_TARGETS = {
    1: "",
    2: "Area of effect over the caster",
    3: "Group teleport",
    4: "Area of effect around the caster",
    5: "Single target",
    6: "Self only",
    8: "Area of effect around the target",
    9: "Animal",
    10: "Undead only",
    11: "Summoned beings",
    13: "Tap",
    14: "Caster's pet",
    15: "Target's corpse",
    16: "Plant",
    17: "Giant",
    18: "Dragon",
    24: "Area of effect on undeads",
    25: "Area of Effect Summoned",
    36: "Area - PC Only",
    40: "Friendly area of effect",
    41: "Group",
}