from django import template

register = template.Library()


@register.filter(name='spell_time_filter')
def spell_time_filter(value):
    try:
        spell_time = float(value / 1000)
    except ValueError:
        spell_time = value
    return spell_time


@register.filter(name='duration_filter')
def duration_filter(value):
    """Returns tick units converted to seconds (6 seconds per tick)"""
    return value * 6


@register.filter(name='zone_types_filter')
def zone_types_filter(value):
    zone_types = {
        -1: "Any",
        0: "Indoor Only",
        1: "Outdoor Only",
        2: "Dungeon Only",
        255: "Any"
    }
    return zone_types[value] if value in zone_types else value


@register.filter(name='resist_type_filter')
def resist_type_filter(value):
    """Convert resist type value to human-readable values"""
    spell_resists = {
        0: "Unresistable",
        1: "Magic",
        2: "Fire",
        3: "Cold",
        4: "Poison",
        5: "Disease",
        6: "Chromatic",
        7: "Prismatic",
        8: "Physical"
    }
    return spell_resists[value] if value in spell_resists else value


@register.filter(name='spell_category_filter')
def spell_category_filter(value):
    spell_categories = {
        -100: "Other (Use Text Field)",
        -99: "NPC",
        -1: "AA Procs",
        0: "Unknown",
        1: "Dir. Dmg [Magic]",
        2: "Dir. Dmg [Undead]",
        3: "Dir. Dmg [Summoned]",
        4: "Dir. Dmg [Lifetaps]",
        5: "Dir. Dmg [Plant]",
        6: "Dir. Dmg [Velious Races]",
        7: "DoT [Magic]",
        8: "DoT [Undead]",
        9: "DoT [Lifetaps]",
        10: "Targeted Ae Dmg",
        11: "PB AE Dmg",
        12: "AE Rain",
        13: "Dir. Dmg [Bolt]",
        14: "Stun [Targeted AE]",
        15: "Stun [Targeted]",
        16: "Stun [PB AE]",
        17: "Drains [HP Mana]",
        18: "Drains [Stats]",
        19: "Contact Innates",
        20: "Heal [Instant]",
        21: "Heal [Duration]",
        22: "Group Heal [Instant]",
        23: "Group Heal [Duration]",
        24: "Regen [Single]",
        25: "Regen [Group]",
        26: "Heal [Own Pet]",
        27: "Resurrect",
        28: "Necro Life Transfer",
        29: "Cure [Poison]",
        30: "HP Buffs [Single]",
        32: "AC Buff [Single]",
        34: "Hate Mod Buffs",
        35: "Haste [Single]",
        36: "Haste [Pet]",
        37: "Haste [Group]",
        38: "Slow [Single]",
        39: "Slow [Targeted Area]",
        40: "Cannabalize",
        41: "Move Speed [Single]",
        42: "Move Speed [Group]",
        43: "Wolf Form",
        44: "Move Speed [Pet]",
        45: "Illusion [Self]",
        46: "Lich",
        47: "Bear Form",
        48: "Tree Form",
        49: "Dead Man Floating",
        50: "Root",
        51: "Summon Pet",
        52: "Summon Corpse",
        53: "Sense Undead",
        54: "Invulnerability",
        55: "Gate [Combat Portal]",
        56: "Gate [Self Gates]",
        58: "Translocate",
        59: "Shadow Step",
        60: "Enchant Item",
        61: "Summon [Misc Item]",
        62: "Fear",
        63: "Fear [Animal]",
        64: "Fear [Undead]",
        65: "Dmg Shield [Single]",
        66: "Dmg Shield [Group]",
        67: "Mark Of Karn",
        68: "Dmg Shield [Self]",
        69: "Resist Debuffs",
        70: "Resist Buffs",
        71: "BST Pet Buffs",
        72: "Summon Familiar",
        73: "STR Buff",
        74: "DEX Buff",
        75: "AGI Buff",
        76: "STA Buff",
        77: "INT Buff",
        78: "CHA Buff",
        79: "Stat Debuffs",
        80: "Invis Undead",
        81: "Invis Animals",
        82: "Invisibility",
        83: "Absorb Damage",
        84: "Casting Level Buffs",
        85: "Clarity Line",
        86: "Max Mana Buffs",
        87: "Drain Mana",
        88: "Mana Transfer",
        89: "Instant Gain Mana",
        90: "Lower Hate [Jolt]",
        91: "Increase Archery",
        92: "ATK Buff",
        93: "Vision",
        94: "Water Breathing",
        95: "Improve Faction",
        96: "Charm",
        97: "Dispell",
        98: "Lull",
        99: "Mezmerise",
        100: "Spell Focus Items",
        101: "Snare [single]",
        102: "Snare [AE]",
        105: "Feign Death",
        106: "Identify",
        107: "Reclaim Energy",
        108: "Find Corpse",
        109: "Summon Player",
        110: "Spell Shield",
        112: "Blindness",
        113: "Levitation",
        114: "Extinquish Fatigue",
        115: "Death Pact",
        116: "Mem Blur",
        118: "Height",
        119: "Add Hate",
        120: "Iron Maiden",
        121: "Focus Spells",
        122: "Melee Guard",
        125: "Dir. Dmg [Fire]",
        126: "Dir. Dmg [Ice]",
        127: "Dir. Dmg [Poison]",
        128: "Dir. Dmg [Disease]",
        129: "DoT [Fire]",
        130: "DoT [Ice]",
        131: "DoT [Poison]",
        132: "DoT [Disease]",
        133: "INT Caster Chest Opening",
        134: "INT Caster Chest Trap Appraisal",
        135: "INT Caster Chest Trap Disarm",
        136: "WIS Caster Chest Trap Disarm",
        137: "WIS Caster Chest Trap Appraisal",
        138: "WIS Caster Chest Opening",
        140: "Destroy [Undead]",
        141: "Destroy [Summoned]",
        142: "Targetted AE [Fire]",
        143: "Targetted AE [Ice]",
        146: "PB AE [Fire]",
        147: "PB AE [Ice]",
        150: "Rain [Fire]",
        151: "Rain [Ice]",
        152: "Rain [Poison]",
        154: "Fear Song",
        155: "Fast Heals",
        156: "Mana to Hitpoints",
        157: "Pet Siphons",
        159: "Cure [Disease]",
        160: "Cure [Curse]",
        161: "Cure [Multiple]",
        162: "Cure [Blind]",
        163: "Group Cure [Multiple]",
        164: "Misc Effects",
        165: "Shielding",
        166: "PAL/RNG/BST HP Buffs",
        167: "Symbols",
        168: "Aegolism Line",
        169: "Paladin AC Buffs",
        170: "Spell Damage Mitigate",
        171: "Spell/Melee Block",
        172: "Spell Reflect",
        173: "Hybrid AC Buffs",
        174: "HP/Mana Regen",
        175: "Aggro Decreasers",
        200: "Misc Spells",
        201: "Disciplines",
        202: "Melee Haste",
        203: "AE Slow",
        204: "Summon Air Pet",
        205: "Summon Water Pet",
        206: "Summon Fire Pet",
        207: "Summon Earth Pet",
        208: "Summon Monster Pet",
        209: "Transport [Antonica]",
        210: "Transport [Odus]",
        211: "Transport [Faydwer]",
        212: "Transport [Kunark]",
        213: "Transport [Velious]",
        214: "Transport [Luclin]",
        215: "Transport [Planes]",
        216: "Transport [Gates/Omens]",
        217: "Summon [Weapon]",
        218: "Summon [Focus]",
        219: "Summon [Food/Drink]",
        220: "Summon [Armor]",
        999: "AA / Abilities",
        1000: "Unknown"
    };
    return spell_categories[value] if value in spell_categories.keys() else value


@register.filter(name='spell_effects_filter')
def spell_effects_filter(value):
    """Convert spell effects value to human-readable values"""
    spell_effects = [
        {"id": "0", "effect": "Increase Hitpoints"},  # or decrease
        {"id": "1", "effect": "Increase AC"},
        {"id": "2", "effect": "Increase ATK"},
        {"id": "3", "effect": "In/Decrease Movement"},
        {"id": "4", "effect": "Increase STR"},
        {"id": "5", "effect": "Increase DEX"},
        {"id": "6", "effect": "Increase AGI"},
        {"id": "7", "effect": "Increase STA"},
        {"id": "8", "effect": "Increase INT"},
        {"id": "9", "effect": "Increase WIS"},
        {"id": "10", "effect": "Increase CHA"},
        {"id": "11", "effect": "In/Decrease Attack Speed"},
        {"id": "12", "effect": "Invisibility"},
        {"id": "13", "effect": "See Invisible"},
        {"id": "14", "effect": "WaterBreathing"},
        {"id": "15", "effect": "Increase Mana"},
        {"id": "18", "effect": "Pacify"},
        {"id": "19", "effect": "Increase Faction"},
        {"id": "20", "effect": "Blindness"},
        {"id": "21", "effect": "Stun"},
        {"id": "22", "effect": "Charm"},
        {"id": "23", "effect": "Fear"},
        {"id": "24", "effect": "Stamina"},
        {"id": "25", "effect": "Bind Affinity"},
        {"id": "26", "effect": "Gate"},
        {"id": "27", "effect": "Cancel Magic"},
        {"id": "28", "effect": "Invisibility versus Undead"},
        {"id": "29", "effect": "Invisibility versus Animals"},
        {"id": "30", "effect": "Frenzy Radius"},
        {"id": "31", "effect": "Mesmerize"},
        {"id": "32", "effect": "Summon Item"},
        {"id": "33", "effect": "Summon Pet:"},
        {"id": "35", "effect": "Increase Disease Counter"},
        {"id": "36", "effect": "Increase Poison Counter"},
        {"id": "40", "effect": "Invunerability"},
        {"id": "41", "effect": "Destroy Target"},
        {"id": "42", "effect": "Shadowstep"},
        {"id": "44", "effect": "Lycanthropy"},
        {"id": "46", "effect": "Increase Fire Resist"},
        {"id": "47", "effect": "Increase Cold Resist"},
        {"id": "48", "effect": "Increase Poison Resist"},
        {"id": "49", "effect": "Increase Disease Resist"},
        {"id": "50", "effect": "Increase Magic Resist"},
        {"id": "52", "effect": "Sense Undead"},
        {"id": "53", "effect": "Sense Summoned"},
        {"id": "54", "effect": "Sense Animals"},
        {"id": "55", "effect": "Increase Absorb Damage"},
        {"id": "56", "effect": "True North"},
        {"id": "57", "effect": "Levitate"},
        {"id": "58", "effect": "Illusion:"},
        {"id": "59", "effect": "Increase Damage Shield"},
        {"id": "61", "effect": "Identify"},
        {"id": "63", "effect": "Memblur"},
        {"id": "64", "effect": "SpinStun"},
        {"id": "65", "effect": "Infravision"},
        {"id": "66", "effect": "Ultravision"},
        {"id": "67", "effect": "Eye Of Zomm"},
        {"id": "68", "effect": "Reclaim Energy"},
        {"id": "69", "effect": "Increase Max Hitpoints"},
        {"id": "71", "effect": "Summon Skeleton Pet:"},
        {"id": "73", "effect": "Bind Sight"},
        {"id": "74", "effect": "Feign Death"},
        {"id": "75", "effect": "Voice Graft"},
        {"id": "76", "effect": "Sentinel"},
        {"id": "77", "effect": "Locate Corpse"},
        {"id": "78", "effect": "Increase Absorb Magic Damage"},
        {"id": "79", "effect": "Increase HP when cast"},
        {"id": "81", "effect": "Resurrect"},
        {"id": "82", "effect": "Summon PC"},
        {"id": "83", "effect": "Teleport"},
        {"id": "84", "effect": "Toss Up"},
        {"id": "85", "effect": "Add Proc:"},
        {"id": "86", "effect": "Reaction Radius"},
        {"id": "87", "effect": "Increase Magnification"},
        {"id": "88", "effect": "Evacuate"},
        {"id": "89", "effect": "Increase Player Size"},
        {"id": "90", "effect": "Cloak"},
        {"id": "91", "effect": "Summon Corpse"},
        {"id": "92", "effect": "Increase hate"},
        {"id": "93", "effect": "Stop Rain"},
        {"id": "94", "effect": "Make Fragile (Delete if combat)"},
        {"id": "95", "effect": "Sacrifice"},
        {"id": "96", "effect": "Silence"},
        {"id": "97", "effect": "Increase Mana Pool"},
        {"id": "98", "effect": "Increase Haste v2"},
        {"id": "99", "effect": "Root"},
        {"id": "100", "effect": "Increase Hitpoints v2"},
        {"id": "101", "effect": "Complete Heal (with duration)"},
        {"id": "102", "effect": "Fearless"},
        {"id": "103", "effect": "Call Pet"},
        {"id": "104", "effect": "Translocates target."},
        {"id": "105", "effect": "Anti-Gate"},
        {"id": "106", "effect": "Summon Warder:"},
        {"id": "108", "effect": "Summon Familiar:"},
        {"id": "109", "effect": "Summon Item v2"},
        {"id": "110", "effect": "Increase Chance to Hit with Archery"},
        {"id": "111", "effect": "Increase All Resists"},
        {"id": "112", "effect": "Increase Effective Casting Level"},
        {"id": "113", "effect": "Summon Horse:"},
        {"id": "114", "effect": "Increase Agro Multiplier"},
        {"id": "115", "effect": "Food/Water"},
        {"id": "116", "effect": "Decrease Curse Counter"},
        {"id": "117", "effect": "Make Weapons Magical"},
        {"id": "118", "effect": "Increase Singing Skill"},
        {"id": "119", "effect": "Increase Haste v3"},
        {"id": "120", "effect": "Set Healing Effectiveness"},
        {"id": "121", "effect": "Reverse Damage Shield"},
        {"id": "123", "effect": "Screech"},
        {"id": "124", "effect": "Increase Spell Damage"},
        {"id": "125", "effect": "Increase Spell Healing"},
        {"id": "127", "effect": "Increase Spell Haste"},
        {"id": "128", "effect": "Increase Spell Duration"},
        {"id": "129", "effect": "Increase Spell Range"},
        {"id": "130", "effect": "Decrease Spell/Bash Hate"},
        {"id": "131", "effect": "Decrease Chance of Using Reagent"},
        {"id": "132", "effect": "Decrease Spell Mana Cost"},
        {"id": "134", "effect": "Limit: Max Level"},
        {"id": "135", "effect": "Limit: Resist(Magic allowed)"},
        {"id": "136", "effect": "Limit: Target"},
        {"id": "137", "effect": "Limit: Effect(Hitpoints allowed)"},
        {"id": "138", "effect": "Limit: Spell Type(Detrimental only)"},
        {"id": "139", "effect": "Limit: Spell"},
        {"id": "140", "effect": "Limit: Min Duration"},
        {"id": "141", "effect": "Limit: Instant spells only"},
        {"id": "142", "effect": "LimitMinLevel"},
        {"id": "143", "effect": "Limit: Min Casting Time"},
        {"id": "145", "effect": "Teleport v2"},
        {"id": "147", "effect": "Increase Hitpoints"},
        {"id": "148", "effect": "Block new spell"},
        {"id": "149", "effect": "Stacking: Overwrite existing spell"},
        {"id": "150", "effect": "Death Save - Restore Partial Health"},
        {"id": "151", "effect": "Suspend Pet - Lose Buffs and Equipment"},
        {"id": "152", "effect": "Summon Pets:"},
        {"id": "153", "effect": "Balance Party Health"},
        {"id": "154", "effect": "Remove Detrimental"},
        {"id": "156", "effect": "Illusion: Target"},
        {"id": "157", "effect": "Spell-Damage Shield"},
        {"id": "158", "effect": "Increase Chance to Reflect Spell"},
        {"id": "159", "effect": "Decrease Stats"},
        {"id": "167", "effect": "Pet Power Increase"},
        {"id": "168", "effect": "Increase Melee Mitigation"},
        {"id": "169", "effect": "Increase Chance to Critical Hit"},
        {"id": "171", "effect": "CrippBlowChance"},
        {"id": "172", "effect": "Increase Chance to Avoid Melee"},
        {"id": "173", "effect": "Increase Chance to Riposte"},
        {"id": "174", "effect": "Increase Chance to Dodge"},
        {"id": "175", "effect": "Increase Chance to Parry"},
        {"id": "176", "effect": "Increase Chance to Dual Wield"},
        {"id": "177", "effect": "Increase Chance to Double Attack"},
        {"id": "178", "effect": "Lifetap from Weapon Damage"},
        {"id": "179", "effect": "Instrument Modifier"},
        {"id": "180", "effect": "Increase Chance to Resist Spell"},
        {"id": "181", "effect": "Increase Chance to Resist Fear Spell"},
        {"id": "182", "effect": "Hundred Hands Effect"},
        {"id": "183", "effect": "Increase All Skills Skill Check"},
        {"id": "184", "effect": "Increase Chance to Hit With all Skills"},
        {"id": "185", "effect": "Increase All Skills Damage Modifier"},
        {"id": "186", "effect": "Increase All Skills Minimum Damage Modifier"},
        {"id": "188", "effect": "Increase Chance to Block"},
        {"id": "192", "effect": "Increase hate"},
        {"id": "194", "effect": "Fade"},
        {"id": "195", "effect": "Stun Resist"},
        {"id": "200", "effect": "Increase Proc Modifier"},
        {"id": "201", "effect": "Increase Range Proc Modifier"},
        {"id": "205", "effect": "Rampage"},
        {"id": "206", "effect": "Area of Effect Taunt"},
        {"id": "216", "effect": "Increase Accuracy"},
        {"id": "227", "effect": "Reduce Skill Timer"},
        {"id": "254", "effect": "Blank"},
        {"id": "266", "effect": "Increase Attack Chance"},
        {"id": "273", "effect": "Increase Critical Dot Chance"},
        {"id": "289", "effect": "Improved Spell Effect: "},
        {"id": "294", "effect": "Increase Critial Spell Chance"},
        {"id": "299", "effect": "Wake the Dead"},
        {"id": "301", "effect": "Increase Archery Damage"},
        {"id": "311", "effect": "Limit: Combat Skills Not Allowed"},
        {"id": "314", "effect": "Fixed Duration Invisbility (not documented on Lucy)"},
        {"id": "323", "effect": "Add Defensive Proc:"},
        {"id": "330", "effect": "Critical Damage Mob"}]
    return spell_effects['id'][value] if value in spell_effects['id'] else value
