# Generated by Django 5.1.4 on 2026-03-21 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dkp', models.DecimalField(decimal_places=1, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('payout_change_history', models.JSONField(default=list)),
                ('npc_id', models.IntegerField(blank=True, null=True)),
                ('npc_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('disputed', 'Disputed'), ('retracted', 'Retracted')], default='pending', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_order', models.JSONField(default=list)),
                ('override_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('bidder_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retracted', 'Retracted'), ('outbid', 'Outbid'), ('lost', 'Lost'), ('won', 'Won'), ('disputed', 'Disputed')], default='active', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.auction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='dkp.bid'),
        ),
        migrations.CreateModel(
            name='CircuitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('member', 'Member')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('current_dkp', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('lifetime_earned_dkp', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('lifetime_spent_dkp', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('hourly_redistribution', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('hide_dashboard', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.circuitmembership'),
        ),
        migrations.AddField(
            model_name='auction',
            name='admin_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctioned_overrides', to='dkp.circuitmembership'),
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('mob_dkp_snapshot', models.JSONField(blank=True, default=dict)),
                ('mobs_awarded', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mobs', models.ManyToManyField(to='dkp.mob')),
            ],
        ),
        migrations.CreateModel(
            name='DKPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('transaction_type', models.CharField(choices=[('award', 'Award'), ('spend', 'Spend'), ('adjustment', 'Adjustment')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.circuitmembership')),
                ('raid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dkp.raid')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dkp.raid'),
        ),
        migrations.CreateModel(
            name='RaidAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('partial_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('early_departure', 'Early Departure'), ('partial', 'Partial'), ('absent', 'Absent')], default='present', max_length=20)),
                ('attendance_notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.circuitmembership')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.raid')),
            ],
            options={
                'unique_together': {('member', 'raid')},
            },
        ),
        migrations.AddField(
            model_name='raid',
            name='members',
            field=models.ManyToManyField(through='dkp.RaidAttendance', to='dkp.circuitmembership'),
        ),
        migrations.CreateModel(
            name='RaidCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='raid',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.raidcircuit'),
        ),
        migrations.AddField(
            model_name='mob',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.raidcircuit'),
        ),
        migrations.CreateModel(
            name='CircuitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public_requested', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_circuit_requests', to=settings.AUTH_USER_MODEL)),
                ('circuit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuit_request', to='dkp.raidcircuit')),
            ],
            options={
                'permissions': [('approve_circuit_request', 'Can approve circuit requests')],
            },
        ),
        migrations.AddField(
            model_name='circuitmembership',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.raidcircuit'),
        ),
        migrations.CreateModel(
            name='CircuitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_bids', models.BooleanField(default=False)),
                ('dkp_cap', models.DecimalField(decimal_places=1, default=50, max_digits=6)),
                ('dkp_overcap', models.DecimalField(decimal_places=1, default=5, max_digits=6)),
                ('minimum_bid', models.DecimalField(decimal_places=1, default=2, max_digits=6)),
                ('new_player_bonus', models.DecimalField(decimal_places=1, default=15, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=1, default=2, max_digits=6)),
                ('tie_breaker_rule', models.CharField(choices=[('earned_dkp', 'Earned DKP'), ('attendance', 'Attendance')], default='earned_dkp', max_length=20)),
                ('attendance_window_days', models.IntegerField(default=90)),
                ('circuit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dkp.raidcircuit')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='dkp.raidcircuit'),
        ),
        migrations.AlterUniqueTogether(
            name='circuitmembership',
            unique_together={('circuit', 'member')},
        ),
        migrations.CreateModel(
            name='RaidMobAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.circuitmembership')),
                ('mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.mob')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkp.raid')),
            ],
            options={
                'unique_together': {('raid', 'mob', 'member')},
            },
        ),
    ]
